spring.application.name=ERP
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}

spring.docker.compose.enabled=false

# Configuracion de inicializacion de datos
spring.datasource.initialization-mode=always
spring.sql.init.mode=always
spring.sql.init.platform=mysql