
DROP TABLE IF EXISTS User_Chat;
DROP TABLE IF EXISTS Message;
DROP TABLE IF EXISTS Chat;
DROP TABLE IF EXISTS AppUser;
DROP TABLE IF EXISTS Role;



CREATE TABLE Role (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    role VARCHAR(255) NOT NULL
);

CREATE TABLE AppUser (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role BIGINT NULL,
    FOREIGN KEY (role) REFERENCES Role(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Message (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NULL,
    FOREIGN KEY (user_id) REFERENCES AppUser(id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Chat (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    visibility VARCHAR(255) NOT NULL
);

CREATE TABLE User_Chat (
    chat_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (chat_id, user_id),
    FOREIGN KEY (chat_id) REFERENCES Chat(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (user_id) REFERENCES AppUser(id) ON DELETE CASCADE ON UPDATE CASCADE
);
